# Generated by Django 3.0.8 on 2020-07-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('view_all_blogs', 'Can view all blogs')], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
