# Generated by Django 3.0.8 on 2020-08-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200729_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
