# Generated by Django 3.0.8 on 2020-07-28 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200728_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='short_description',
            new_name='summary',
        ),
    ]
