# Generated by Django 3.1 on 2020-08-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, default='old dojo', null=True),
        ),
    ]
