# Generated by Django 3.0.8 on 2020-07-15 20:25

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    replaces = [('closings', '0001_initial'), ('closings', '0002_auto_20200714_1335'), ('closings', '0003_auto_20200714_1556'), ('closings', '0004_auto_20200714_1729'), ('closings', '0005_auto_20200714_1834')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.State')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='closings.City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.State')),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.Firm')),
                ('firm_location', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='firm', chained_model_field='firm', on_delete=django.db.models.deletion.CASCADE, to='closings.FirmLocation')),
            ],
        ),
        migrations.AlterField(
            model_name='firmlocation',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.Firm'),
        ),
        migrations.AlterField(
            model_name='firmlocation',
            name='city',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='state', on_delete=django.db.models.deletion.CASCADE, to='closings.City'),
        ),
    ]
