# Generated by Django 3.0.8 on 2020-07-14 20:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='closings.City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.State')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
