# Generated by Django 3.0.8 on 2020-07-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='friends',
            field=models.ManyToManyField(related_name='_employee_friends_+', to='closings.Employee'),
        ),
    ]
