# Generated by Django 3.0.8 on 2020-07-14 22:56

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0002_auto_20200714_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.Firm')),
                ('firm_location', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='firm', chained_model_field='firm', on_delete=django.db.models.deletion.CASCADE, to='closings.FirmLocation')),
            ],
        ),
        migrations.AlterField(
            model_name='firmlocation',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closings.Firm'),
        ),
    ]
