# Generated by Django 3.0.8 on 2020-07-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0002_employee_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_set', to='closings.Employee')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_set', to='closings.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='trainees',
            field=models.ManyToManyField(related_name='trainers', through='closings.Training', to='closings.Employee'),
        ),
    ]
