# Generated by Django 3.0.8 on 2020-07-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0003_auto_20200714_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
