# Generated by Django 3.0.8 on 2020-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closings', '0003_auto_20200718_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workers',
            field=models.ManyToManyField(related_name='supervisors', to='closings.Employee'),
        ),
    ]
